// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA365PvSy2n_NnFINFKJk-V6f7Mi_7GNlA',
    appId: '1:1004125818437:web:3de61ea9f77b99256fdd2c',
    messagingSenderId: '1004125818437',
    projectId: 'chat-app-6f208',
    authDomain: 'chat-app-6f208.firebaseapp.com',
    storageBucket: 'chat-app-6f208.appspot.com',
    measurementId: 'G-RYY93NK4ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaqBwn11ULJfbY7nOcB_zwrTBV90GaRqI',
    appId: '1:1004125818437:android:dfe21515fe8b4dae6fdd2c',
    messagingSenderId: '1004125818437',
    projectId: 'chat-app-6f208',
    storageBucket: 'chat-app-6f208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFb6BaLPMyfGMhPrLiNgt14enFH5H7vQ4',
    appId: '1:1004125818437:ios:3f6b9bf1977471e96fdd2c',
    messagingSenderId: '1004125818437',
    projectId: 'chat-app-6f208',
    storageBucket: 'chat-app-6f208.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFb6BaLPMyfGMhPrLiNgt14enFH5H7vQ4',
    appId: '1:1004125818437:ios:447353dd2300aa616fdd2c',
    messagingSenderId: '1004125818437',
    projectId: 'chat-app-6f208',
    storageBucket: 'chat-app-6f208.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
